### ISSUE TITLE
hash of generated file mismatch with Scio

### ISSUE THREAD

**Issue by ckchow** [spotify/scio-idea-plugin#14]
It seems like there's still some mismatch between where the plugin expects to find the generated case class and where Scio actually puts it:

plugin error: `test-cbe9dbcc.scala`
scio generated name: `test-3a237b59.scala`

**Comment by ravwojdyla** [comment]
hi @ckchow thanks for reporting! Could you please share the versions of scala/scio-plugin/scio/intellij?

**Comment by ckchow** [comment]
scio-plugin: `0.1.10`
scio: `0.4.5` and `0.4.6`

intellij: 
>  IntelliJ IDEA 2017.3.2 (Community Edition)
>   Build #IC-173.4127.27, built on December 25, 2017
>    JRE: 1.8.0_152-release-1024-b8 x86_64
>    JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
 >   Mac OS X 10.12.6

I think it might be an intellij-related problem because the plugin was working fine on the last version.

**Comment by ckchow** [comment]
Ok, I don't think this is a real regression. I deleted the cached json schema in `.bigquery` and scio refetched a new version of the schema (which I had modified) and everything seems fine. I guess this is more of a scio issue / non-issue. I'll close this if that seems reasonable.

**Comment by regadas** [comment]
This hasn't been reported in awhile and the plugin was refactored recently. Let's close this and reopen if needed.
