### ISSUE TITLE
queryAsSource method not appearing on classes annotated with BigQueryType.fromSchema

### ISSUE THREAD

**Issue by thecav** [spotify/scio-idea-plugin#240]
As the title suggests, classes annocated with `@BigQueryType.fromSchema` have a `queryAsSource()` method added (see https://github.com/spotify/scio/pull/2804/files ) however this plugin doesn't add that method and IntelliJ see it as an error wrt autocomplete.

I have a potential fix in a fork here: https://github.com/thecav/scio-idea-plugin/tree/fix-fromquery-queryassource-autocomplete

Currently testing, but I think that should address this issue.

**Comment by sendcraig** [comment]
+1 - I also experienced this issue when using IntelliJ and following [the data engineering golden path](https://backstage.spotify.net/docs/default/component/data-engineering-golden-path/part-2-creating-and-running-a-data-pipeline/7-lets-start-coding/#track)

**Comment by kellen** [comment]
@thecav please open a PR and we'll test & merge

**Comment by camenares** [comment]
@thecav was there anything from the testing not working yet?
