### ISSUE TITLE
BigQuery.fromTable annotation does not have format function.

### ISSUE THREAD

**Issue by richwhitjr** [spotify/scio-idea-plugin#8]
I recent PR fixed most issues with missing functions on BigQuery macros in Intellij.  I am still seeing issues with the format function on the @BigQueryType.toTable annotation.  For example when you do the following you see a read line saying format is a missing function.

```scala
// Shows format does not exist.
Foo.table.format
```

This however does work fine in the case of queries.(@BigQueryType.fromQuery)

```scala
// Looks good in IntelliJ.
Foo.query.format
```

**Comment by nevillelyh** [comment]
https://github.com/spotify/scio-idea-plugin/blob/master/src/main/scala/com/spotify/scio/ScioInjector.scala#L120

It's a `def table: TableReference`, not a string, so this is expected.

**Comment by nevillelyh** [comment]
Looks like a bug after all. We are generating `def table: String` in https://github.com/spotify/scio/blob/master/scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/TypeProvider.scala#L47

**Comment by ravwojdyla** [comment]
Ah - yes - that changed in scio via https://github.com/spotify/scio/pull/329 will submit PR. Thanks for reporting @richwhitjr !

**Comment by ravwojdyla** [comment]
@richwhitjr and `0.1.6` is now available in idea repository, you should just update the plugin.

**Comment by richwhitjr** [comment]
Great thanks!
